# Generated by Django 4.0.2 on 2022-02-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='category name')),
                ('is_out', models.BooleanField(verbose_name='is out')),
                ('craetion_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='update datetime')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='payment type name')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='update datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='source name')),
                ('balance', models.PositiveIntegerField(verbose_name='balance')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='update datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='transaction date')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('is_creadit', models.BooleanField(verbose_name='is creadit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.category')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.paymenttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.source')),
            ],
        ),
    ]
